import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdir, mkdtemp, readFile, realpath, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import os from 'node:os';
import path from 'node:path';
import { app, BrowserWindow, WebContentsView, session, ipcMain } from 'electron';
import { OwnedBrowserHost } from '../../desktop/browser-host.mjs';
import { removeOwnedBrowserState } from '../../rhwp/rhwp-agent/browser-cleanup.mjs';
import { createOwnedBrowserService } from '../../rhwp/rhwp-agent/owned-browser-service.mjs';

const require = createRequire(new URL('../../rhwp/rhwp-agent/package.json', import.meta.url));
const { chromium } = require('playwright-core');
console.error('OWNED_BROWSER_STAGE modules-loaded');
const fail = (error) => { console.error(error?.stack ?? error); process.exit(1); };
process.on('uncaughtException', fail);
process.on('unhandledRejection', fail);
const root = await realpath(process.env.RHWP_BROWSER_TEST_DATA_DIR || await mkdtemp(path.join(os.tmpdir(), 'hama-owned-browser-')));
app.setPath('userData', path.join(root, 'electron'));
app.on('window-all-closed', () => {});
const report = {};
let host;
let browser;
let proxy;
let service;
let serviceHost;
let serviceSite;
const windows = new Map();
const html = '<!doctype html><title>Owned research fixture</title><h1>Native research page</h1><label>Draft <input id="draft"></label><label>Password <input id="password" type="password"></label><a href="/second">Next page</a><button id="download">Download PDF</button><script>document.querySelector("#download").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["%PDF-1.4\\nOwned authenticated bytes\\n%%EOF"],{type:"application/pdf"}));a.download="native.pdf";a.click()};</script>';

app.whenReady().then(async () => {
try {
  console.error('OWNED_BROWSER_STAGE ready');
  // This proxy serves only a bounded fixture. No website or existing profile is used.
  proxy = createServer((request, response) => {
    if (request.headers['proxy-authorization'] !== `Basic ${Buffer.from('fixture:owned').toString('base64')}`) {
      response.writeHead(407, { 'proxy-authenticate': 'Basic realm="Owned fixture"' }); response.end(); return;
    }
    const url = new URL(request.url);
    if (url.hostname !== 'browser-fixture.invalid') { response.writeHead(403); response.end(); return; }
    response.writeHead(200, { 'content-type': 'text/html', 'set-cookie': 'ownedLogin=shared; Path=/; SameSite=Lax' });
    response.end(url.pathname === '/second' ? '<!doctype html><title>Second page</title><h1>Second page</h1>' : html);
  });
  await new Promise((resolve) => proxy.listen(0, '127.0.0.1', resolve));
  const first = new BrowserWindow({ show: false, webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false } });
  const second = new BrowserWindow({ show: false, webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false } });
  windows.set('window-one', first); windows.set('window-two', second);
  first.show();
  const owner = { id: 'fixture-hub-1' };
  const events = [];
  host = new OwnedBrowserHost({ BrowserWindow, WebContentsView, electronSession: session, dataDir: path.join(root, 'browser-data'), getWindowForSession: (id) => windows.get(id), onEvent: (event) => events.push(event) });
  ipcMain.handle('desktop:browser-popout-command', (event, payload) => host.popoutCommand(event.sender, payload));
  const settings = { profileDir: path.join(root, 'browser-data', 'browser', 'native-profile'), proxy: { server: `http://127.0.0.1:${proxy.address().port}`, username: 'fixture', password: 'owned' } };
  const native = await host.start(settings, owner);
  console.error('OWNED_BROWSER_STAGE host-started');
  browser = await chromium.connectOverCDP(native.endpointURL, { timeout: 15_000 });
  const context = browser.contexts()[0];
  const page = await context.newPage();
  await page.goto('http://browser-fixture.invalid/', { waitUntil: 'domcontentloaded' });
  assert.equal(await page.locator('h1').innerText(), 'Native research page');
  const initialViewport = await page.evaluate(() => ({ width: innerWidth, height: innerHeight }));
  assert.ok(initialViewport.width > 0 && initialViewport.height > 0);
  assert.ok((await page.screenshot()).length > 0);
  report.unattachedCapture = { ...initialViewport, captured: true };
  const cdp = await context.newCDPSession(page);
  const { targetInfo } = await cdp.send('Target.getTargetInfo');
  await cdp.detach();
  host.bind({ targetId: targetInfo.targetId, tabId: 'tab-one', sessionId: 'window-one', chatId: 'chat-one' });
  console.error('OWNED_BROWSER_STAGE page-bound');
  await page.locator('#draft').fill('Kept while moving');
  await page.evaluate(() => localStorage.setItem('owned-note', 'persisted'));
  const bridge = await page.evaluate(() => ({ desktop: typeof window.rhwpDesktop, presentation: typeof window.ownedBrowserPresentation, node: typeof require }));
  assert.deepEqual(bridge, { desktop: 'undefined', presentation: 'undefined', node: 'undefined' });
  report.guestIsolation = bridge;
  let navigations = 0; page.on('framenavigated', (frame) => { if (frame === page.mainFrame()) navigations++; });
  host.attach(first, { tabId: 'tab-one', bounds: { x: 10, y: 80, width: 620, height: 410 }, mode: 'dock' });
  host.detach(first, { tabId: 'tab-one' });
  host.attach(first, { tabId: 'tab-one', bounds: { x: 20, y: 100, width: 500, height: 360 }, mode: 'float' });
  await page.waitForFunction(() => innerWidth === 500 && innerHeight === 360);
  host.attach(first, { tabId: 'tab-one', bounds: { x: 160, y: 120, width: 420, height: 300 }, mode: 'float' });
  await page.waitForFunction(() => innerWidth === 420 && innerHeight === 300);
  assert.deepEqual(host.tab('tab-one').view.getBounds(), { x: 160, y: 120, width: 420, height: 300 });
  assert.equal(await page.locator('#draft').inputValue(), 'Kept while moving');
  host.attach(first, { tabId: 'tab-one', bounds: { x: 20, y: 100, width: 500, height: 360 }, mode: 'float' });
  await page.waitForFunction(() => innerWidth === 500 && innerHeight === 360);
  host.control({ tabId: 'tab-one', human: true });
  const floatContents = host.tab('tab-one').view.webContents;
  await page.locator('#draft').focus();
  floatContents.focus();
  host.attach(first, { tabId: 'tab-one', bounds: { x: 24, y: 104, width: 500, height: 360 }, mode: 'float', interactive: true });
  assert.equal(floatContents.isFocused(), true, 'Moving the live view must preserve keyboard focus');
  floatContents.sendInputEvent({ type: 'keyDown', keyCode: 'X' });
  floatContents.sendInputEvent({ type: 'char', keyCode: 'x' });
  floatContents.sendInputEvent({ type: 'keyUp', keyCode: 'X' });
  await page.waitForFunction(() => document.querySelector('#draft').value === 'Kept while movingx');
  host.detach(first, { tabId: 'tab-one' });
  assert.equal(host.state(host.tab('tab-one')).mode, 'hidden');
  assert.equal(page.isClosed(), false);
  assert.equal(await page.locator('#draft').inputValue(), 'Kept while movingx');
  assert.ok((await page.screenshot()).length > 0);
  host.control({ tabId: 'tab-one', human: false });
  await page.locator('#draft').fill('Kept while moving');
  host.attach(first, { tabId: 'tab-one', bounds: { x: 10, y: 80, width: 620, height: 410 }, mode: 'dock' });
  assert.equal(host.state(host.tab('tab-one')).mode, 'dock');
  report.floatingPresentation = { humanInput: true, moveResizeMatchesViewport: true, hidePreservesPage: true, hiddenCapture: true, dockRestoresPage: true };
  host.attach(first, { tabId: 'tab-one', mode: 'popout' });
  const popout = host.popouts.get(targetInfo.targetId);
  if (popout.webContents.isLoading()) await new Promise((resolve) => popout.webContents.once('did-finish-load', resolve));
  await popout.webContents.executeJavaScript('document.querySelector("#close").click()');
  assert.equal(host.state(host.tab('tab-one')).mode, 'hidden');
  assert.equal(popout.isDestroyed(), false);
  assert.equal(popout.isVisible(), false);
  report.popoutClosePreservesPage = true;
  host.attach(first, { tabId: 'tab-one', bounds: { x: 10, y: 80, width: 620, height: 410 }, mode: 'dock' });
  assert.equal(await page.locator('#draft').inputValue(), 'Kept while moving');
  assert.equal(navigations, 0);
  report.presentation = { navigations, draft: await page.locator('#draft').inputValue(), mode: host.state(host.tab('tab-one')).mode };
  console.error('OWNED_BROWSER_STAGE presentations');
  assert.throws(() => host.attach(second, { tabId: 'tab-one', bounds: { x: 0, y: 0, width: 200, height: 200 } }), /another editor window/);
  await assert.rejects(() => host.navigate(first, { tabId: 'tab-one', url: 'http://browser-fixture.invalid/second' }), /Take control/);
  host.control({ tabId: 'tab-one', owner: 'human' });
  await host.navigate(first, { tabId: 'tab-one', url: 'http://browser-fixture.invalid/second' });
  assert.equal(await page.locator('h1').innerText(), 'Second page');
  host.navigation(first, { tabId: 'tab-one' }, 'back');
  await page.waitForURL('http://browser-fixture.invalid/');
  host.control({ tabId: 'tab-one', human: false });
  await page.locator('#draft').fill('Agent still has input');
  assert.equal(await page.locator('#draft').inputValue(), 'Agent still has input');
  const contents = host.tab('tab-one').view.webContents;
  let physicalBlocked = false;
  const checkPhysicalInput = (event) => { physicalBlocked ||= event.defaultPrevented; };
  contents.on('before-input-event', checkPhysicalInput);
  contents.sendInputEvent({ type: 'keyDown', keyCode: 'X' });
  contents.sendInputEvent({ type: 'char', keyCode: 'x' });
  contents.sendInputEvent({ type: 'keyUp', keyCode: 'X' });
  await page.evaluate(() => true);
  contents.off('before-input-event', checkPhysicalInput);
  assert.equal(physicalBlocked, true);
  assert.equal(await page.locator('#draft').inputValue(), 'Agent still has input');
  host.control({ tabId: 'tab-one', human: true });
  await page.locator('#draft').focus();
  contents.focus();
  contents.sendInputEvent({ type: 'keyDown', keyCode: 'X' });
  contents.sendInputEvent({ type: 'char', keyCode: 'x' });
  contents.sendInputEvent({ type: 'keyUp', keyCode: 'X' });
  await page.waitForFunction(() => document.querySelector('#draft').value === 'Agent still has inputx');
  host.control({ tabId: 'tab-one', human: false });
  report.control = { agentInput: true, nativeHumanNavigation: true, crossWindowRejected: true };
  report.control.physicalInputBlocked = physicalBlocked;
  report.control.physicalHumanInput = true;
  console.error('OWNED_BROWSER_STAGE control');
  const pageTwo = await context.newPage();
  await pageTwo.goto('http://browser-fixture.invalid/');
  assert.ok(await pageTwo.evaluate(() => document.cookie.includes('ownedLogin=shared')));
  report.sharedAuthentication = true;
  // Route interception is required for account/network authorization, not just navigation.
  await context.route('**/*', (route) => route.continue());
  await page.goto('http://browser-fixture.invalid/');
  assert.equal(await page.locator('h1').innerText(), 'Native research page');
  report.routeInterception = true;
  console.error('OWNED_BROWSER_STAGE route');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#download').click();
  const download = await downloadPromise;
  const downloadPath = await download.path();
  assert.match(await readFile(downloadPath, 'utf8'), /^%PDF-1\.4/);
  report.download = { filename: download.suggestedFilename(), bytes: (await readFile(downloadPath)).length };
  console.error('OWNED_BROWSER_STAGE download');
  await page.locator('#draft').fill('Survives hub restart');
  const screenshotPath = process.env.RHWP_BROWSER_EVIDENCE_PATH;
  if (screenshotPath) { await writeFile(screenshotPath, await page.screenshot()); report.screenshot = screenshotPath; }
  await browser.close(); browser = null;
  console.error('OWNED_BROWSER_STAGE client-closed');
  await host.release(owner);
  console.error('OWNED_BROWSER_STAGE host-released');
  assert.equal(host.tab('tab-one').view.webContents.isDestroyed(), false);
  const restartedOwner = { id: 'fixture-hub-2' };
  const restarted = await host.start(settings, restartedOwner);
  console.error('OWNED_BROWSER_STAGE host-restarted');
  assert.notEqual(restarted.endpointURL, native.endpointURL);
  browser = await chromium.connectOverCDP(restarted.endpointURL);
  console.error('OWNED_BROWSER_STAGE client-reconnected');
  const restoredPages = browser.contexts()[0].pages();
  console.error(`OWNED_BROWSER_STAGE restored-pages-${restoredPages.length}`);
  const drafts = await Promise.all(restoredPages.map((value) => value.evaluate(() => document.querySelector('#draft')?.value)));
  console.error('OWNED_BROWSER_STAGE restored-drafts');
  assert.ok(drafts.includes('Survives hub restart'));
  assert.equal(await restoredPages[drafts.indexOf('Survives hub restart')].evaluate(() => localStorage.getItem('owned-note')), 'persisted');
  console.error('OWNED_BROWSER_STAGE restored-storage');
  report.hubRestart = { guestsSurvived: true, retainedForm: true, endpointRotated: true };
  assert.ok(events.some((event) => event.type === 'runtime-disconnected'));
  contents.openDevTools({ mode: 'detach', activate: false });
  console.error('OWNED_BROWSER_STAGE devtools-attempted');
  assert.equal(await contents.executeJavaScript('document.querySelector("#draft").value'), 'Survives hub restart');
  assert.equal(contents.isDestroyed(), false);
  assert.equal(contents.isDevToolsOpened(), false);
  assert.equal(contents.debugger.isAttached(), true);
  assert.equal(await restoredPages[drafts.indexOf('Survives hub restart')].locator('#draft').inputValue(), 'Survives hub restart');
  report.debuggerOwnership = { devtoolsDisabled: true, debuggerRetained: true, guestPreserved: true };
  await browser.close(); browser = null;
  await host.release(restartedOwner);
  const staleReset = await host.handleRequest({ type: 'rhwp-browser-request', id: 'stale-reset', operation: 'reset' }, owner);
  assert.equal(staleReset.ok, false);
  const reset = await host.handleRequest({ type: 'rhwp-browser-request', id: 'browser-reset', operation: 'reset' }, restartedOwner);
  assert.equal(reset.ok, true, reset.error?.message);
  assert.equal(reset.value.tabsClosed, 2);
  assert.equal(host.tabs.size, 0);
  assert.equal(host.popouts.size, 0);
  assert.deepEqual(await host.session.cookies.get({}), []);
  await writeFile(path.join(root, 'browser-data', 'browser-policy.json'), JSON.stringify({ schema: 1, ownerId: 'fixture-owner', accounts: [] }));
  await removeOwnedBrowserState({ dataDir: path.join(root, 'browser-data') });
  const resetRuntime = await host.start(settings, restartedOwner);
  browser = await chromium.connectOverCDP(resetRuntime.endpointURL);
  const resetContext = browser.contexts()[0];
  assert.equal(resetContext.pages().length, 0);
  assert.deepEqual(await resetContext.cookies(), []);
  const cleanPage = await resetContext.newPage();
  await cleanPage.goto('http://browser-fixture.invalid/');
  assert.equal(await cleanPage.evaluate(() => localStorage.getItem('owned-note')), null);
  report.browserReset = { staleOwnerRejected: true, releasedOwnerAllowed: true, guestsClosed: true, cookiesCleared: true, profileDeleted: true, storageClearedAfterRestart: true };
  console.error('OWNED_BROWSER_STAGE browser-reset');
  serviceSite = createServer((_request, response) => { response.setHeader('content-type', 'text/html'); response.end('<title>Recovered native tab</title><input id="draft">'); });
  await new Promise((resolve) => serviceSite.listen(0, '127.0.0.1', resolve));
  const serviceOrigin = `http://127.0.0.1:${serviceSite.address().port}`;
  const serviceDir = path.join(root, 'native-service');
  const serviceOwner = { id: 'service-hub' };
  serviceHost = new OwnedBrowserHost({ BrowserWindow, WebContentsView, electronSession: session, dataDir: serviceDir, getWindowForSession: (id) => windows.get(id) });
  const adapter = {
    async start(settings) { return { ...await serviceHost.start(settings, serviceOwner), close: () => serviceHost.release(serviceOwner) }; },
    bind: (args) => serviceHost.bind(args), control: (args) => serviceHost.control(args),
  };
  await mkdir(path.join(serviceDir, 'browser'), { recursive: true });
  await writeFile(path.join(serviceDir, 'browser', 'tabs.json'), JSON.stringify({ version: 1, tabs: [
    { tabId: 'restored-tab', threadId: 'chat-one', agentId: 'owner', sessionId: 'previous-editor-session', url: serviceOrigin, title: 'Recovered native tab' },
  ] }));
  service = createOwnedBrowserService({ dataDir: serviceDir, nativeAdapter: adapter, workspaceTargets: [serviceOrigin] });
  await service.restore();
  const recovered = await service.request({ isHuman: true, clientId: 'window-one', sessionId: 'window-one', threadId: 'chat-one', agentId: 'owner' }, 'recover', { tabId: 'restored-tab' });
  assert.equal(recovered.runtime.kind, 'native');
  assert.equal(serviceHost.state(serviceHost.tab('restored-tab')).controller, 'human');
  serviceHost.attach(first, { tabId: 'restored-tab', bounds: { x: 0, y: 80, width: 500, height: 360 }, interactive: true });
  assert.equal(serviceHost.tab('restored-tab').interactive, true);
  const recoveredContents = serviceHost.tab('restored-tab').view.webContents;
  // Prepare the native backing surface before focusing it for physical input.
  await recoveredContents.capturePage();
  first.show();
  first.focus();
  await recoveredContents.executeJavaScript('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
  await recoveredContents.executeJavaScript('document.querySelector("#draft").focus()', true);
  recoveredContents.focus();
  recoveredContents.sendInputEvent({ type: 'mouseDown', x: 20, y: 20, button: 'left', clickCount: 1 });
  recoveredContents.sendInputEvent({ type: 'mouseUp', x: 20, y: 20, button: 'left', clickCount: 1 });
  recoveredContents.sendInputEvent({ type: 'keyDown', keyCode: 'X' });
  recoveredContents.sendInputEvent({ type: 'char', keyCode: 'x' });
  recoveredContents.sendInputEvent({ type: 'keyUp', keyCode: 'X' });
  const value = await recoveredContents.executeJavaScript(`new Promise((resolve) => {
    const field = document.querySelector('#draft');
    if (field.value === 'x') { resolve(field.value); return; }
    const timer = setTimeout(() => resolve(field.value), 2000);
    field.addEventListener('input', () => { clearTimeout(timer); resolve(field.value); }, { once: true });
  })`);
  assert.equal(value, 'x');
  report.nativeDefaultRecovery = { native: true, currentEditorBinding: true, humanInput: true };
  report.runtime = 'Electron WebContentsView + private CDP + Playwright';
  report.fixtureUrl = 'http://browser-fixture.invalid/';
} catch (error) { report.error = error.stack ?? String(error); }
finally {
  await service?.close().catch(() => {});
  await serviceHost?.dispose().catch(() => {});
  serviceSite?.closeAllConnections();
  if (serviceSite) await new Promise((resolve) => serviceSite.close(resolve));
  await browser?.close().catch(() => {});
  console.error('OWNED_BROWSER_STAGE cleanup-client');
  await host?.dispose().catch(() => {});
  console.error('OWNED_BROWSER_STAGE cleanup-host');
  for (const window of windows.values()) if (!window.isDestroyed()) window.destroy();
  console.error('OWNED_BROWSER_STAGE cleanup-windows');
  proxy?.closeAllConnections();
  if (proxy) await new Promise((resolve) => proxy.close(resolve));
  console.error('OWNED_BROWSER_STAGE cleanup-proxy');
  console.log(`OWNED_BROWSER_REPORT ${JSON.stringify(report)}`);
  app.exit(report.error ? 1 : 0);
}
});
