// rhwp 도구 공유 규칙 — 의존성 없는 순수 텍스트 모듈.
/**
 * 모든 rhwp 도구가 공유하는 규칙 — 도구 설명마다 반복하지 않고 여기서 한 번만 말한다.
 * MCP 서버 instructions(mcp-stdio.mjs)와 provider 브리프(agents/backend.mjs)가 둘 다
 * 이 텍스트를 싣고, 도구 설명은 "rhwp tool rules" 한 줄 포인터만 남긴다.
 */
export const RHWP_TOOL_RULES = `RHWP TOOL RULES (shared by every rhwp document tool; tool descriptions point here):
- Addresses: sectionIdx, paraIdx and charOffset are 0-based body coordinates. Get them from get_structure, find_text or get_selection.
- Revision: every document read returns the current revision. Every document write needs expectedRevision, the revision from your most recent rhwp tool call. REVISION_MISMATCH carries the current revision; follow the recovery guidance in the error message. Chain each write's returned revision into the next write and never send writes in parallel. Disjoint-paragraph writes from sibling agents are rebased automatically (the response carries rebasedParaShift), so a mismatch is a real conflict.
- Batching: when you know two or more edits, send ONE apply_edits call (up to 32 items). Items run in order on the evolving document — a later item's coordinates and anchors resolve against the text left by earlier items, so order matters only where an earlier edit changes the text a later one points at. Batch independent reads the same way with read_batch (up to 16 read tools in one call; each item returns its own result or error and one item's failure never aborts the rest).
- Cheap reads: get_structure defaults to compact text; pass range {sectionIdx, fromPara, toPara} for a slice, or sinceRevision for only the paragraphs changed since that revision plus a shift map for the rest. FULL_REFRESH_REQUIRED means the gap is no longer tracked — re-read without sinceRevision and keep the new revision.
- Anchors: insert_text, delete_range, replace_range, apply_char_format and apply_para_format take anchor {text, occurrence?, within?{sectionIdx?, paraRange?[firstPara,lastPara], cell?{paraIdx,controlIdx,cellIdx}}, position? before|after|replace} instead of coordinates — never pass both. The match is resolved at execution time: exactly one match applies, several matches need occurrence (1-based) or within, and no match or an ambiguous match fails listing up to 5 candidates. position picks where the target lands — insert_text: before/after the match (default after; replace overwrites it), the range tools and apply_char_format take the match itself, apply_para_format takes the match's paragraph (before/after for the adjacent paragraph).
- Staging: document writes, apply_engine_edits batches included, are staged as a live preview — every op applies at the call, so what you read or render is what gets committed. After a successful turn they auto-commit (전체 접근) or wait for the user's review and approval (안전); a turn that ends without success also waits in review — the user keeps or discards them, they are never silently rolled back. Committed edits stay undoable. If a tool result carries editReport or a turn opens with a staged_edit_report block, staged edits were discarded or stayed in the document after a rejection — re-read those parts before editing them again.
- Write results: every staged write and apply_edits returns after {paragraphs (touched text, up to 8 × 200 chars; from = first offset shown when not 0), pageCountBefore, pageCount, pages (0-based pageIndex touched), warnings?}. warnings appear only for layout problems — a table running past the page body (with the fix) or paragraphs outside the edit pushed to another page; fix them when unintended. render:"crop" adds one PNG of just the changed areas stacked top to bottom (renderRegions lists each area's page), render:"page" the touched pages. verify_changes is an optional review summary; skip it when after has no warnings.
- Offsets: charOffset counts text characters only, in body and cells alike. Inline objects (equations, pictures, tables) take no offset, and text inserted at an object's offset lands before the object. Use offsets from find_text or get_selection instead of counting what you see.
- Table cells: to target text inside a cell, pass cell {paraIdx, controlIdx, cellIdx}. paraIdx/controlIdx come from the get_structure table line ("table s0 p5 c0 …" gives paraIdx 5, controlIdx 0) and cellIdx from its [cellIdx] grid; cellIdx is the row-major index where merged cells count once. A find_text match carries a complete cell you can copy as-is. For a nested cell, also pass cellPath [{controlIndex, cellIndex, cellParaIndex}, …] from find_text or get_selection (its last cellParaIndex is replaced by the tool's paraIdx). With cell, paraIdx/startParaIdx/endParaIdx and offsets are relative to the innermost cell.
- Units: lengths in mm, font sizes in pt, colors "#RRGGBB". An A4 body with default margins is about 150mm wide.`;
