import type { FileSystemFileHandleLike } from '../command/file-system-access.ts';

// A grant is attached to the exact byte view produced by one handle read. It is
// process-local, non-serializable, and consumed before parsing, so copied,
// replayed, remote, history, and generated bytes remain on the 128 MiB path.
const exactLocalReads = new WeakMap<Uint8Array, FileSystemFileHandleLike>();

export function markExactLocalFileRead(
  bytes: Uint8Array,
  handle: FileSystemFileHandleLike,
): void {
  exactLocalReads.set(bytes, handle);
}

export function consumeExactLocalFileRead(
  bytes: Uint8Array,
  handle: FileSystemFileHandleLike | null,
): boolean {
  if (!handle || exactLocalReads.get(bytes) !== handle) return false;
  exactLocalReads.delete(bytes);
  return true;
}
