import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';

/** Production sidebar with a typed local browser fixture. Runtime checks run in the owned-browser e2e. */
export async function checkBrowserWorkbench({ page, origin, screenshot }) {
  await page.setViewport({ width: 1440, height: 1000, deviceScaleFactor: 1 });
  await page.goto(`${origin}/?reset=1&controls=0&scenario=chat&fullscreen=1&theme=dark`, { waitUntil: 'networkidle0' });
  await page.waitForFunction(() => window.sidebarPreview && !document.querySelector('.ag-input').disabled);
  await page.click('.ag-workspace-panel-btn');
  await page.click('.ag-workbench-launcher-item[data-view="browser"]');
  await page.waitForSelector('.ag-browser:not([hidden])', { visible: true });
  await page.click('[aria-label="연구 브라우저 열기"]');
  await page.waitForFunction(() => document.querySelector('.ag-browser-frame')?.src.startsWith('data:image/jpeg'));
  const original = await page.evaluate(() => window.sidebarPreview.snapshot().browser.tabs[0].tabId);
  await page.click('.ag-browser [aria-label="직접 조작"]');
  await page.waitForFunction(() => window.sidebarPreview.snapshot().browser.tabs[0].controller.owner === 'human');
  await page.focus('.ag-browser-ime');
  await page.keyboard.down('Control'); await page.keyboard.press('l'); await page.keyboard.up('Control');
  assert.equal(await page.evaluate(() => document.activeElement === document.querySelector('.ag-browser-address')), true, 'browser address shortcut leaves page input and focuses navigation');
  await page.evaluate(() => {
    const input = document.querySelector('.ag-browser-ime'); input.focus();
    input.dispatchEvent(new CompositionEvent('compositionstart', { data: '', bubbles: true }));
    input.value = '한글 자료';
    input.dispatchEvent(new InputEvent('input', { data: '한글 자료', isComposing: true, bubbles: true }));
    input.dispatchEvent(new CompositionEvent('compositionend', { data: '한글 자료', bubbles: true }));
    input.dispatchEvent(new InputEvent('input', { data: '한글 자료', inputType: 'insertText', bubbles: true }));
  });
  await page.waitForFunction(() => window.sidebarPreview.snapshot().browser.inputs.some(input => input.text === '한글 자료'));
  assert.equal(await page.evaluate(() => window.sidebarPreview.snapshot().browser.inputs.filter(input => input.text === '한글 자료').length), 1, 'Korean composition sends final text once');
  const dockedColors = await page.$eval('.ag-browser', element => ({ background: getComputedStyle(element).backgroundColor, color: getComputedStyle(element).color }));
  await page.click('.ag-browser [aria-label="브라우저 띄우기"]');
  await page.waitForSelector('.ag-browser-floating:not([hidden]) .ag-browser', { visible: true });
  assert.equal(await page.evaluate(() => window.sidebarPreview.snapshot().browser.tabs[0].tabId), original, 'floating retains the runtime tab');
  assert.deepEqual(await page.$eval('.ag-browser-floating .ag-browser', element => ({ background: getComputedStyle(element).backgroundColor, color: getComputedStyle(element).color })), dockedColors, 'floating retains readable application theme colors');
  if (screenshot) await screenshot('browser-workbench-float-dark');
  await page.click('.ag-browser [aria-label="브라우저 추가 메뉴"]');
  await page.waitForSelector('.ag-browser-details[open] .ag-browser-menu', { visible: true });
  assert.equal(await page.$eval('.ag-browser-menu', element => element.textContent.includes('preview-owned-browser') || element.textContent.includes('chromium')), true, 'More exposes runtime diagnostics');
  if (screenshot) await screenshot('browser-workbench-more');
  await page.keyboard.press('Escape');
  assert.equal(await page.$eval('.ag-browser-details', element => element.open), false, 'Escape dismisses More and keeps browser presentation');
  await page.evaluate(() => { const theme = document.querySelector('#theme'); theme.value = 'light'; theme.dispatchEvent(new Event('change', { bubbles: true })); });
  await page.waitForFunction(() => document.documentElement.dataset.themeEffective === 'light');
  if (screenshot) await screenshot('browser-workbench-float-light');
  await page.evaluate(() => { const theme = document.querySelector('#theme'); theme.value = 'dark'; theme.dispatchEvent(new Event('change', { bubbles: true })); });
  await page.click('.ag-browser [aria-label="작업 칸에 붙이기"]');
  await page.waitForSelector('.ag-workbench-panel[data-view="browser"] .ag-browser', { visible: true });
  assert.equal(await page.evaluate(() => window.sidebarPreview.snapshot().browser.tabs[0].tabId), original, 'docking retains the runtime tab');
  if (screenshot) await screenshot('browser-workbench-docked');
  await page.click('.ag-browser [aria-label="페이지·개체·영역에 의견 붙이기"]');
  await page.click('.ag-browser [aria-label="영역 선택"]');
  const frame = await page.$('.ag-browser-frame'); const bounds = await frame.boundingBox();
  await page.mouse.move(bounds.x + bounds.width * .1, bounds.y + bounds.height * .2);
  await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width * .5, bounds.y + bounds.height * .5); await page.mouse.up();
  await page.type('.ag-browser [aria-label="자료 의견"]', '이 영역의 근거를 확인해 주세요.');
  if (screenshot) await screenshot('browser-workbench-region-comment');
  await page.click('.ag-browser [aria-label="의견과 자료를 선택한 채팅에 첨부"]');
  await page.waitForSelector('.ag-capture-inbox [data-capture-id]');
  const capture = await page.evaluate(() => window.sidebarPreview.snapshot().browser.captures.at(-1));
  assert.equal(capture.mode, 'region'); assert.ok(capture.rect.width > 0 && capture.rect.height > 0);
  assert.equal(capture.comment, '이 영역의 근거를 확인해 주세요.');
  assert.equal(await page.evaluate(() => window.sidebarPreview.snapshot().messagesSent), 0, 'capture stages attachments without sending chat');
  await page.click('.ag-browser [aria-label="브라우저 보기 닫기"]');
  assert.equal(await page.evaluate(() => window.sidebarPreview.snapshot().browser.tabs.length), 1, 'hiding presentation leaves browser available');
  await page.click('.ag-workbench-tabs [data-view="browser"]');
  await page.waitForSelector('.ag-browser:not([hidden])', { visible: true });
  await page.click('.ag-browser [aria-label="브라우저 띄우기"]');
  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 });
  await page.waitForFunction(() => document.querySelector('.ag-browser-floating').getBoundingClientRect().width <= innerWidth);
  const viewport = await page.$eval('.ag-browser-floating', element => ({ x: element.getBoundingClientRect().x, width: element.getBoundingClientRect().width }));
  assert.equal(viewport.x, 0); assert.ok(viewport.width <= 390);
  if (screenshot) await screenshot('browser-workbench-mobile');
  await page.click('.ag-browser [aria-label="브라우저 보기 닫기"]');
  await page.setViewport({ width: 1440, height: 1000, deviceScaleFactor: 1 });
  await page.goto(`${origin}/?reset=1&controls=0&scenario=chat&theme=dark`, { waitUntil: 'networkidle0' });
  await page.waitForFunction(() => window.sidebarPreview && !document.querySelector('.ag-input').disabled);
  await page.click('.ag-browser-trigger');
  await page.waitForSelector('.ag-browser-floating:not([hidden]) .ag-browser', { visible: true });
  assert.equal(await page.$eval('.ag-root', element => element.classList.contains('ag-fullscreen')), false, 'in-app float opens from the normal editor sidebar');
  await page.click('.ag-browser [aria-label="연구 브라우저 열기"]');
  await page.waitForFunction(() => document.querySelector('.ag-browser-frame')?.src.startsWith('data:image/jpeg'));
  const floatingTab = await page.evaluate(() => window.sidebarPreview.snapshot().browser.tabs[0].tabId);
  await page.focus('.ag-input'); await page.keyboard.type('자료를 읽어 주세요');
  assert.equal(await page.$eval('.ag-input', element => element.value), '자료를 읽어 주세요', 'underlying chat remains editable while the browser floats');
  await page.focus('.ag-browser-move');
  const beforeMove = await page.$eval('.ag-browser-floating', element => element.getBoundingClientRect().left);
  await page.keyboard.press('ArrowRight');
  const afterMove = await page.$eval('.ag-browser-floating', element => element.getBoundingClientRect().left);
  assert.ok(afterMove > beforeMove, 'floating browser can be positioned with the keyboard');
  if (screenshot) await page.screenshot({ path: fileURLToPath(new URL('./artifacts/browser-workbench-editor-float.png', import.meta.url)) });
  for (let attempt = 0; attempt < 30; attempt++) await page.keyboard.press('ArrowDown');
  const bounded = await page.$eval('.ag-browser-floating', element => ({ bottom: element.getBoundingClientRect().bottom, height: innerHeight }));
  assert.ok(bounded.bottom <= bounded.height + 1, 'keyboard positioning keeps the full PiP within the app window');
  await page.click('.ag-browser [aria-label="브라우저 보기 닫기"]');
  assert.equal(await page.evaluate(() => window.sidebarPreview.snapshot().browser.tabs[0].tabId), floatingTab, 'hiding an editor float retains the same browser tab');
  await page.click('.ag-browser-trigger');
  await page.waitForSelector('.ag-browser-floating:not([hidden]) .ag-browser', { visible: true });
  assert.equal(await page.evaluate(() => window.sidebarPreview.snapshot().browser.tabs[0].tabId), floatingTab, 'reopening an editor float reuses the same browser tab');
  await page.click('.ag-browser [aria-label="브라우저 추가 메뉴"]');
  await page.waitForSelector('.ag-browser-details[open] [aria-label="별도 창으로 열기"]', { visible: true });
  await page.keyboard.press('Escape');
  await page.click('.ag-browser [aria-label="작업 칸에 붙이기"]');
  await page.waitForFunction(() => document.querySelector('.ag-root').classList.contains('ag-fullscreen') && document.querySelector('.ag-workbench-panel[data-view="browser"] .ag-browser')?.getBoundingClientRect().width > 0 && !document.body.classList.contains('ag-fs-vt'));
  assert.equal(await page.evaluate(() => window.sidebarPreview.snapshot().browser.tabs[0].tabId), floatingTab, 'docking from the normal editor preserves the same tab after fullscreen transition');
  await page.click('.ag-browser [aria-label="브라우저 추가 메뉴"]');
  await page.waitForSelector('.ag-browser-details[open] [aria-label="별도 창으로 열기"]', { visible: true });
  const popupPromise = new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('More action did not open the browser window')), 10000);
    page.once('popup', popup => { clearTimeout(timeout); resolve(popup); });
  });
  await page.click('.ag-browser [aria-label="별도 창으로 열기"]');
  const popup = await popupPromise;
  await popup.waitForSelector('.ag-browser[data-presentation="popout"]', { visible: true });
  assert.equal(await page.evaluate(() => window.sidebarPreview.snapshot().browser.tabs[0].tabId), floatingTab, 'optional browser window retains the same runtime tab');
  await popup.waitForSelector('.ag-browser [aria-label="작업 칸에 붙이기"]', { visible: true });
  const popupDock = await popup.$eval('.ag-browser [aria-label="작업 칸에 붙이기"]', button => { const rect = button.getBoundingClientRect(); return { x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 }; });
  await popup.mouse.click(popupDock.x, popupDock.y);
  await page.waitForSelector('.ag-workbench-panel[data-view="browser"] .ag-browser[data-presentation="dock"]', { visible: true });
  assert.equal(await page.evaluate(() => window.sidebarPreview.snapshot().browser.tabs[0].tabId), floatingTab, 'returning from the optional window preserves the same tab');
  await page.click('.ag-browser [aria-label="브라우저 보기 닫기"]');
}
