/** Generated by scripts/generate-agent-edit-capabilities.mjs. Do not edit manually. */
export const ENGINE_EDIT_CAPABILITIES = [
  {
    "method": "addBookmark",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "name"
    ],
    "signature": "addBookmark(sec: number, para: number, charOffset: number, name: string)"
  },
  {
    "method": "applyCellStyle",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "styleId"
    ],
    "signature": "applyCellStyle(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, styleId: number)"
  },
  {
    "method": "applyCharFormat",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "startOffset",
      "endOffset",
      "propsJson"
    ],
    "signature": "applyCharFormat(sec: number, para: number, startOffset: number, endOffset: number, propsJson: string)"
  },
  {
    "method": "applyCharFormatAcrossSections",
    "kind": "document",
    "parameters": [
      "startSec",
      "startPara",
      "startOffset",
      "endSec",
      "endPara",
      "endOffset",
      "propsJson"
    ],
    "signature": "applyCharFormatAcrossSections(startSec: number, startPara: number, startOffset: number, endSec: number, endPara: number, endOffset: number, propsJson: string)"
  },
  {
    "method": "applyCharFormatInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "startOffset",
      "endOffset",
      "propsJson"
    ],
    "signature": "applyCharFormatInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, startOffset: number, endOffset: number, propsJson: string)"
  },
  {
    "method": "applyCharFormatInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "startOffset",
      "endOffset",
      "propsJson"
    ],
    "signature": "applyCharFormatInCellByPath(sec: number, parentPara: number, pathJson: string, startOffset: number, endOffset: number, propsJson: string)"
  },
  {
    "method": "applyCharFormatInFootnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "control",
      "notePara",
      "start",
      "end",
      "props"
    ],
    "signature": "applyCharFormatInFootnote(sec: number, para: number, control: number, notePara: number, start: number, end: number, props: string)"
  },
  {
    "method": "applyCharFormatInHeaderFooter",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "startHfParaIdx",
      "startOffset",
      "endHfParaIdx",
      "endOffset",
      "propsJson"
    ],
    "signature": "applyCharFormatInHeaderFooter(sec: number, isHeader: boolean, applyTo: number, startHfParaIdx: number, startOffset: number, endHfParaIdx: number, endOffset: number, propsJson: string,)"
  },
  {
    "method": "applyCharFormatInHf",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "para",
      "start",
      "end",
      "props"
    ],
    "signature": "applyCharFormatInHf(sec: number, isHeader: boolean, applyTo: number, para: number, start: number, end: number, props: string)"
  },
  {
    "method": "applyEndnoteShape",
    "kind": "document",
    "parameters": [
      "sec",
      "settings"
    ],
    "signature": "applyEndnoteShape(sec: number, settings: EndnoteShapeSettings)"
  },
  {
    "method": "applyHfTemplate",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "templateId"
    ],
    "signature": "applyHfTemplate(sec: number, isHeader: boolean, applyTo: number, templateId: number)"
  },
  {
    "method": "applyParaFormat",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "propsJson"
    ],
    "signature": "applyParaFormat(sec: number, para: number, propsJson: string)"
  },
  {
    "method": "applyParaFormatAcrossSections",
    "kind": "document",
    "parameters": [
      "startSec",
      "startPara",
      "endSec",
      "endPara",
      "propsJson"
    ],
    "signature": "applyParaFormatAcrossSections(startSec: number, startPara: number, endSec: number, endPara: number, propsJson: string)"
  },
  {
    "method": "applyParaFormatInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "propsJson"
    ],
    "signature": "applyParaFormatInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, propsJson: string)"
  },
  {
    "method": "applyParaFormatInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "path",
      "props"
    ],
    "signature": "applyParaFormatInCellByPath(sec: number, parentPara: number, path: string, props: string)"
  },
  {
    "method": "applyParaFormatInFootnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "controlIdx",
      "fnParaIdx",
      "propsJson"
    ],
    "signature": "applyParaFormatInFootnote(sec: number, para: number, controlIdx: number, fnParaIdx: number, propsJson: string)"
  },
  {
    "method": "applyParaFormatInHf",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "hfParaIdx",
      "propsJson"
    ],
    "signature": "applyParaFormatInHf(sec: number, isHeader: boolean, applyTo: number, hfParaIdx: number, propsJson: string)"
  },
  {
    "method": "applyStyle",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "styleId"
    ],
    "signature": "applyStyle(sec: number, para: number, styleId: number)"
  },
  {
    "method": "assignPictureImage",
    "kind": "document",
    "parameters": [
      "sec",
      "parentParaIdx",
      "cellPathJson",
      "controlIdx",
      "imageData",
      "naturalWidthPx",
      "naturalHeightPx",
      "extension"
    ],
    "signature": "assignPictureImage(sec: number, parentParaIdx: number, cellPathJson: string, controlIdx: number, imageData: Uint8Array, naturalWidthPx: number, naturalHeightPx: number, extension: string)"
  },
  {
    "method": "changeObjectZOrder",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci",
      "operation"
    ],
    "signature": "changeObjectZOrder(sec: number, para: number, ci: number, operation: string)"
  },
  {
    "method": "clearTableCellRange",
    "kind": "document",
    "parameters": [
      "sec",
      "parent",
      "pathJson",
      "startRow",
      "startCol",
      "endRow",
      "endCol"
    ],
    "signature": "clearTableCellRange(sec: number, parent: number, pathJson: string, startRow: number, startCol: number, endRow: number, endCol: number)"
  },
  {
    "method": "copyControl",
    "kind": "session",
    "parameters": [
      "sec",
      "para",
      "ci",
      "cellPathJson"
    ],
    "signature": "copyControl(sec: number, para: number, ci: number, cellPathJson = '')"
  },
  {
    "method": "copySelection",
    "kind": "session",
    "parameters": [
      "sec",
      "startPara",
      "startOffset",
      "endPara",
      "endOffset"
    ],
    "signature": "copySelection(sec: number, startPara: number, startOffset: number, endPara: number, endOffset: number)"
  },
  {
    "method": "copySelectionAcrossSections",
    "kind": "session",
    "parameters": [
      "startSec",
      "startPara",
      "startOffset",
      "endSec",
      "endPara",
      "endOffset"
    ],
    "signature": "copySelectionAcrossSections(startSec: number, startPara: number, startOffset: number, endSec: number, endPara: number, endOffset: number)"
  },
  {
    "method": "copySelectionInCell",
    "kind": "session",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "startCellPara",
      "startOffset",
      "endCellPara",
      "endOffset"
    ],
    "signature": "copySelectionInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, startCellPara: number, startOffset: number, endCellPara: number, endOffset: number)"
  },
  {
    "method": "copySelectionInCellByPath",
    "kind": "session",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "startCellPara",
      "startOffset",
      "endCellPara",
      "endOffset"
    ],
    "signature": "copySelectionInCellByPath(sec: number, parentPara: number, pathJson: string, startCellPara: number, startOffset: number, endCellPara: number, endOffset: number)"
  },
  {
    "method": "copyTableCellRange",
    "kind": "session",
    "parameters": [
      "sec",
      "parent",
      "pathJson",
      "startRow",
      "startCol",
      "endRow",
      "endCol"
    ],
    "signature": "copyTableCellRange(sec: number, parent: number, pathJson: string, startRow: number, startCol: number, endRow: number, endCol: number)"
  },
  {
    "method": "copyTableCellsTransposed",
    "kind": "session",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "startRow",
      "startCol",
      "endRow",
      "endCol"
    ],
    "signature": "copyTableCellsTransposed(sec: number, parentPara: number, controlIdx: number, startRow: number, startCol: number, endRow: number, endCol: number,)"
  },
  {
    "method": "createHeaderFooter",
    "kind": "document",
    "parameters": [
      "sectionIdx",
      "isHeader",
      "applyTo"
    ],
    "signature": "createHeaderFooter(sectionIdx: number, isHeader: boolean, applyTo: number)"
  },
  {
    "method": "createNumbering",
    "kind": "document",
    "parameters": [
      "json"
    ],
    "signature": "createNumbering(json: string)"
  },
  {
    "method": "createShapeControl",
    "kind": "document",
    "parameters": [
      "params"
    ],
    "signature": "createShapeControl(params: Record<string, unknown>)"
  },
  {
    "method": "createStyle",
    "kind": "document",
    "parameters": [
      "json"
    ],
    "signature": "createStyle(json: string)"
  },
  {
    "method": "createTable",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "rows",
      "cols"
    ],
    "signature": "createTable(sec: number, para: number, charOffset: number, rows: number, cols: number)"
  },
  {
    "method": "createTableEx",
    "kind": "document",
    "parameters": [
      "options"
    ],
    "signature": "createTableEx(options: { sectionIdx: number; paraIdx: number; charOffset: number; rowCount: number; colCount: number; treatAsChar?: boolean; colWidths?: number[]; rowHeights?: number[]; })"
  },
  {
    "method": "deleteBookmark",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ctrlIdx"
    ],
    "signature": "deleteBookmark(sec: number, para: number, ctrlIdx: number)"
  },
  {
    "method": "deleteCellPictureControlByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "cellPath",
      "innerControlIdx"
    ],
    "signature": "deleteCellPictureControlByPath(sec: number, parentPara: number, cellPath: CellPathLike, innerControlIdx: number,)"
  },
  {
    "method": "deleteCellTableControlByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "controlIdx"
    ],
    "signature": "deleteCellTableControlByPath(sec: number, parentPara: number, pathJson: string, controlIdx: number)"
  },
  {
    "method": "deleteEquationControl",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci"
    ],
    "signature": "deleteEquationControl(sec: number, para: number, ci: number)"
  },
  {
    "method": "deleteEquationControlInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "eqControlIdx"
    ],
    "signature": "deleteEquationControlInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, eqControlIdx: number)"
  },
  {
    "method": "deleteEquationControlInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "cellPath",
      "eqControlIdx"
    ],
    "signature": "deleteEquationControlInCellByPath(sec: number, parentPara: number, cellPath: CellPathLike, eqControlIdx: number)"
  },
  {
    "method": "deleteFootnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "controlIdx"
    ],
    "signature": "deleteFootnote(sec: number, para: number, controlIdx: number)"
  },
  {
    "method": "deleteHeaderFooter",
    "kind": "document",
    "parameters": [
      "sectionIdx",
      "isHeader",
      "applyTo"
    ],
    "signature": "deleteHeaderFooter(sectionIdx: number, isHeader: boolean, applyTo: number)"
  },
  {
    "method": "deleteParagraph",
    "kind": "document",
    "parameters": [
      "sec",
      "para"
    ],
    "signature": "deleteParagraph(sec: number, para: number)"
  },
  {
    "method": "deletePictureControl",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci"
    ],
    "signature": "deletePictureControl(sec: number, para: number, ci: number)"
  },
  {
    "method": "deleteRange",
    "kind": "document",
    "parameters": [
      "sec",
      "startPara",
      "startOffset",
      "endPara",
      "endOffset",
      "logical"
    ],
    "signature": "deleteRange(sec: number, startPara: number, startOffset: number, endPara: number, endOffset: number, logical = false)"
  },
  {
    "method": "deleteRangeAcrossSections",
    "kind": "document",
    "parameters": [
      "startSec",
      "startPara",
      "startOffset",
      "endSec",
      "endPara",
      "endOffset",
      "logical"
    ],
    "signature": "deleteRangeAcrossSections(startSec: number, startPara: number, startOffset: number, endSec: number, endPara: number, endOffset: number, logical = false)"
  },
  {
    "method": "deleteRangeInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "startCellPara",
      "startOffset",
      "endCellPara",
      "endOffset"
    ],
    "signature": "deleteRangeInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, startCellPara: number, startOffset: number, endCellPara: number, endOffset: number)"
  },
  {
    "method": "deleteRangeInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "startPara",
      "startOffset",
      "endPara",
      "endOffset",
      "logical"
    ],
    "signature": "deleteRangeInCellByPath(sec: number, parentPara: number, pathJson: string, startPara: number, startOffset: number, endPara: number, endOffset: number, logical = false)"
  },
  {
    "method": "deleteShapeControl",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci"
    ],
    "signature": "deleteShapeControl(sec: number, para: number, ci: number)"
  },
  {
    "method": "deleteStyle",
    "kind": "document",
    "parameters": [
      "styleId"
    ],
    "signature": "deleteStyle(styleId: number)"
  },
  {
    "method": "deleteTableColumn",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "colIdx"
    ],
    "signature": "deleteTableColumn(sec: number, parentPara: number, controlIdx: number, colIdx: number)"
  },
  {
    "method": "deleteTableColumnByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "colIdx"
    ],
    "signature": "deleteTableColumnByPath(sec: number, parentPara: number, pathJson: string, colIdx: number)"
  },
  {
    "method": "deleteTableControl",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx"
    ],
    "signature": "deleteTableControl(sec: number, parentPara: number, controlIdx: number)"
  },
  {
    "method": "deleteTableRow",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "rowIdx"
    ],
    "signature": "deleteTableRow(sec: number, parentPara: number, controlIdx: number, rowIdx: number)"
  },
  {
    "method": "deleteTableRowByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "rowIdx"
    ],
    "signature": "deleteTableRowByPath(sec: number, parentPara: number, pathJson: string, rowIdx: number)"
  },
  {
    "method": "deleteText",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "count",
      "logical"
    ],
    "signature": "deleteText(sec: number, para: number, charOffset: number, count: number, logical = false)"
  },
  {
    "method": "deleteTextInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "charOffset",
      "count",
      "logical"
    ],
    "signature": "deleteTextInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, charOffset: number, count: number, logical = false)"
  },
  {
    "method": "deleteTextInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "charOffset",
      "count",
      "logical"
    ],
    "signature": "deleteTextInCellByPath(sec: number, parentPara: number, pathJson: string, charOffset: number, count: number, logical = false)"
  },
  {
    "method": "deleteTextInCellDeferredPagination",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "charOffset",
      "count",
      "logical"
    ],
    "signature": "deleteTextInCellDeferredPagination(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, charOffset: number, count: number, logical = false)"
  },
  {
    "method": "deleteTextInFootnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "controlIdx",
      "fnParaIdx",
      "charOffset",
      "count"
    ],
    "signature": "deleteTextInFootnote(sec: number, para: number, controlIdx: number, fnParaIdx: number, charOffset: number, count: number)"
  },
  {
    "method": "deleteTextInHeaderFooter",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "hfParaIdx",
      "charOffset",
      "count"
    ],
    "signature": "deleteTextInHeaderFooter(sec: number, isHeader: boolean, applyTo: number, hfParaIdx: number, charOffset: number, count: number)"
  },
  {
    "method": "ensureDefaultBullet",
    "kind": "document",
    "parameters": [
      "bulletChar"
    ],
    "signature": "ensureDefaultBullet(bulletChar: string)"
  },
  {
    "method": "ensureDefaultNumbering",
    "kind": "document",
    "parameters": [],
    "signature": "ensureDefaultNumbering()"
  },
  {
    "method": "evaluateTableFormula",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "targetRow",
      "targetCol",
      "formula",
      "writeResult"
    ],
    "signature": "evaluateTableFormula(sec: number, parentPara: number, controlIdx: number, targetRow: number, targetCol: number, formula: string, writeResult: boolean)"
  },
  {
    "method": "evaluateTableFormulaEx",
    "kind": "document",
    "parameters": [
      "options"
    ],
    "signature": "evaluateTableFormulaEx(options: { sectionIdx: number; parentParaIdx: number; controlIdx: number; targetRow: number; targetCol: number; formula: string; writeResult: boolean; decimalPlaces?: number; thousandsSeparator?: boolean; prefix?: string; suffix?: string; })"
  },
  {
    "method": "findOrCreateFontId",
    "kind": "document",
    "parameters": [
      "name"
    ],
    "signature": "findOrCreateFontId(name: string)"
  },
  {
    "method": "findOrCreateFontIdForLang",
    "kind": "document",
    "parameters": [
      "lang",
      "name"
    ],
    "signature": "findOrCreateFontIdForLang(lang: number, name: string)"
  },
  {
    "method": "fitTableToPage",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx"
    ],
    "signature": "fitTableToPage(sec: number, parentPara: number, controlIdx: number)"
  },
  {
    "method": "groupShapes",
    "kind": "document",
    "parameters": [
      "sec",
      "targets"
    ],
    "signature": "groupShapes(sec: number, targets: { paraIdx: number; controlIdx: number }[])"
  },
  {
    "method": "insertClickHereField",
    "kind": "document",
    "parameters": [
      "pos",
      "guide",
      "memo",
      "name",
      "editable"
    ],
    "signature": "insertClickHereField(pos: DocumentPosition, guide: string, memo: string, name: string, editable: boolean,)"
  },
  {
    "method": "insertColumnBreak",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset"
    ],
    "signature": "insertColumnBreak(sec: number, para: number, charOffset: number)"
  },
  {
    "method": "insertEndnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset"
    ],
    "signature": "insertEndnote(sec: number, para: number, charOffset: number)"
  },
  {
    "method": "insertEquation",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "script",
      "fontSizeHwpunit",
      "color"
    ],
    "signature": "insertEquation(sec: number, para: number, charOffset: number, script: string, fontSizeHwpunit: number, color: number)"
  },
  {
    "method": "insertEquationInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "charOffset",
      "script",
      "fontSizeHwpunit",
      "color"
    ],
    "signature": "insertEquationInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, charOffset: number, script: string, fontSizeHwpunit: number, color: number)"
  },
  {
    "method": "insertEquationInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "cellPath",
      "charOffset",
      "script",
      "fontSizeHwpunit",
      "color"
    ],
    "signature": "insertEquationInCellByPath(sec: number, parentPara: number, cellPath: CellPathLike, charOffset: number, script: string, fontSizeHwpunit: number, color: number)"
  },
  {
    "method": "insertFieldInHf",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "hfParaIdx",
      "charOffset",
      "fieldType"
    ],
    "signature": "insertFieldInHf(sec: number, isHeader: boolean, applyTo: number, hfParaIdx: number, charOffset: number, fieldType: number)"
  },
  {
    "method": "insertFootnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset"
    ],
    "signature": "insertFootnote(sec: number, para: number, charOffset: number)"
  },
  {
    "method": "insertHyperlink",
    "kind": "document",
    "parameters": [
      "target",
      "start",
      "end",
      "uri"
    ],
    "signature": "insertHyperlink(target: HyperlinkTarget, start: number, end: number, uri: string)"
  },
  {
    "method": "insertNewNumber",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "startNum"
    ],
    "signature": "insertNewNumber(sec: number, para: number, charOffset: number, startNum: number)"
  },
  {
    "method": "insertPageBreak",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset"
    ],
    "signature": "insertPageBreak(sec: number, para: number, charOffset: number)"
  },
  {
    "method": "insertParagraph",
    "kind": "document",
    "parameters": [
      "sec",
      "para"
    ],
    "signature": "insertParagraph(sec: number, para: number)"
  },
  {
    "method": "insertPicture",
    "kind": "document",
    "parameters": [
      "sec",
      "paraIdx",
      "charOffset",
      "cellPathJson",
      "imageData",
      "width",
      "height",
      "naturalWidthPx",
      "naturalHeightPx",
      "extension",
      "description",
      "paperOffsetXHu",
      "paperOffsetYHu",
      "placement"
    ],
    "signature": "insertPicture(sec: number, paraIdx: number, charOffset: number, cellPathJson: string, imageData: Uint8Array, width: number, height: number, naturalWidthPx: number, naturalHeightPx: number, extension: string, description: string = '', paperOffsetXHu?: number, paperOffsetYHu?: number, placement?: 'inline' | 'floating')"
  },
  {
    "method": "insertTableColumn",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "colIdx",
      "right"
    ],
    "signature": "insertTableColumn(sec: number, parentPara: number, controlIdx: number, colIdx: number, right: boolean)"
  },
  {
    "method": "insertTableColumnByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "colIdx",
      "right"
    ],
    "signature": "insertTableColumnByPath(sec: number, parentPara: number, pathJson: string, colIdx: number, right: boolean)"
  },
  {
    "method": "insertTableRow",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "rowIdx",
      "below"
    ],
    "signature": "insertTableRow(sec: number, parentPara: number, controlIdx: number, rowIdx: number, below: boolean)"
  },
  {
    "method": "insertTableRowByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "rowIdx",
      "below"
    ],
    "signature": "insertTableRowByPath(sec: number, parentPara: number, pathJson: string, rowIdx: number, below: boolean)"
  },
  {
    "method": "insertText",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "text",
      "logical"
    ],
    "signature": "insertText(sec: number, para: number, charOffset: number, text: string, logical = false)"
  },
  {
    "method": "insertTextInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "charOffset",
      "text",
      "logical"
    ],
    "signature": "insertTextInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, charOffset: number, text: string, logical = false)"
  },
  {
    "method": "insertTextInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "charOffset",
      "text",
      "logical"
    ],
    "signature": "insertTextInCellByPath(sec: number, parentPara: number, pathJson: string, charOffset: number, text: string, logical = false)"
  },
  {
    "method": "insertTextInCellDeferredPagination",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "charOffset",
      "text",
      "logical"
    ],
    "signature": "insertTextInCellDeferredPagination(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, charOffset: number, text: string, logical = false)"
  },
  {
    "method": "insertTextInFootnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "controlIdx",
      "fnParaIdx",
      "charOffset",
      "text"
    ],
    "signature": "insertTextInFootnote(sec: number, para: number, controlIdx: number, fnParaIdx: number, charOffset: number, text: string)"
  },
  {
    "method": "insertTextInHeaderFooter",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "hfParaIdx",
      "charOffset",
      "text"
    ],
    "signature": "insertTextInHeaderFooter(sec: number, isHeader: boolean, applyTo: number, hfParaIdx: number, charOffset: number, text: string)"
  },
  {
    "method": "insertTextLogical",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "logicalOffset",
      "text"
    ],
    "signature": "insertTextLogical(sec: number, para: number, logicalOffset: number, text: string)"
  },
  {
    "method": "mergeParagraph",
    "kind": "document",
    "parameters": [
      "sec",
      "para"
    ],
    "signature": "mergeParagraph(sec: number, para: number)"
  },
  {
    "method": "mergeParagraphInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx"
    ],
    "signature": "mergeParagraphInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number)"
  },
  {
    "method": "mergeParagraphInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson"
    ],
    "signature": "mergeParagraphInCellByPath(sec: number, parentPara: number, pathJson: string)"
  },
  {
    "method": "mergeParagraphInFootnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "controlIdx",
      "fnParaIdx"
    ],
    "signature": "mergeParagraphInFootnote(sec: number, para: number, controlIdx: number, fnParaIdx: number)"
  },
  {
    "method": "mergeParagraphInHeaderFooter",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "hfParaIdx"
    ],
    "signature": "mergeParagraphInHeaderFooter(sec: number, isHeader: boolean, applyTo: number, hfParaIdx: number)"
  },
  {
    "method": "mergeTableCells",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "startRow",
      "startCol",
      "endRow",
      "endCol"
    ],
    "signature": "mergeTableCells(sec: number, parentPara: number, controlIdx: number, startRow: number, startCol: number, endRow: number, endCol: number)"
  },
  {
    "method": "mergeTableCellsByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "startRow",
      "startCol",
      "endRow",
      "endCol"
    ],
    "signature": "mergeTableCellsByPath(sec: number, parentPara: number, pathJson: string, startRow: number, startCol: number, endRow: number, endCol: number)"
  },
  {
    "method": "moveLineEndpoint",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci",
      "sx",
      "sy",
      "ex",
      "ey"
    ],
    "signature": "moveLineEndpoint(sec: number, para: number, ci: number, sx: number, sy: number, ex: number, ey: number)"
  },
  {
    "method": "movePictureControl",
    "kind": "document",
    "parameters": [
      "sec",
      "fromPara",
      "fromCi",
      "toPara",
      "toCharOffset"
    ],
    "signature": "movePictureControl(sec: number, fromPara: number, fromCi: number, toPara: number, toCharOffset: number,)"
  },
  {
    "method": "movePictureControlByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "fromParentPara",
      "fromPath",
      "fromControl",
      "toParentPara",
      "toPath",
      "toCharOffset"
    ],
    "signature": "movePictureControlByPath(sec: number, fromParentPara: number, fromPath: CellPathLike, fromControl: number, toParentPara: number, toPath: CellPathLike, toCharOffset: number,)"
  },
  {
    "method": "moveTableOffset",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "deltaH",
      "deltaV"
    ],
    "signature": "moveTableOffset(sec: number, parentPara: number, controlIdx: number, deltaH: number, deltaV: number)"
  },
  {
    "method": "pasteControl",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset"
    ],
    "signature": "pasteControl(sec: number, para: number, charOffset: number)"
  },
  {
    "method": "pasteDocumentBlock",
    "kind": "document",
    "parameters": [
      "sourceBytes",
      "sourceSection",
      "startPara",
      "endPara",
      "targetSection",
      "targetPara",
      "targetCharOffset"
    ],
    "signature": "pasteDocumentBlock(sourceBytes: Uint8Array, sourceSection: number, startPara: number, endPara: number, targetSection: number, targetPara: number, targetCharOffset: number,)"
  },
  {
    "method": "pasteHtml",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "html"
    ],
    "signature": "pasteHtml(sec: number, para: number, charOffset: number, html: string)"
  },
  {
    "method": "pasteHtmlInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "charOffset",
      "html"
    ],
    "signature": "pasteHtmlInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, charOffset: number, html: string)"
  },
  {
    "method": "pasteHtmlInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "charOffset",
      "html"
    ],
    "signature": "pasteHtmlInCellByPath(sec: number, parentPara: number, pathJson: string, charOffset: number, html: string)"
  },
  {
    "method": "pasteHwpJson",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "json"
    ],
    "signature": "pasteHwpJson(sec: number, para: number, charOffset: number, json: string)"
  },
  {
    "method": "pasteInternal",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset"
    ],
    "signature": "pasteInternal(sec: number, para: number, charOffset: number)"
  },
  {
    "method": "pasteInternalInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "charOffset"
    ],
    "signature": "pasteInternalInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, charOffset: number)"
  },
  {
    "method": "pasteInternalInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "charOffset"
    ],
    "signature": "pasteInternalInCellByPath(sec: number, parentPara: number, pathJson: string, charOffset: number)"
  },
  {
    "method": "pasteTableCellRange",
    "kind": "document",
    "parameters": [
      "sec",
      "parent",
      "pathJson",
      "startRow",
      "startCol"
    ],
    "signature": "pasteTableCellRange(sec: number, parent: number, pathJson: string, startRow: number, startCol: number)"
  },
  {
    "method": "pasteTableCellsTransposed",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "startRow",
      "startCol"
    ],
    "signature": "pasteTableCellsTransposed(sec: number, parentPara: number, controlIdx: number, startRow: number, startCol: number,)"
  },
  {
    "method": "pasteTableCellsTransposedAsTable",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset"
    ],
    "signature": "pasteTableCellsTransposedAsTable(sec: number, para: number, charOffset: number,)"
  },
  {
    "method": "promoteOleEquation",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci"
    ],
    "signature": "promoteOleEquation(sec: number, para: number, ci: number)"
  },
  {
    "method": "reflowLinesegs",
    "kind": "document",
    "parameters": [],
    "signature": "reflowLinesegs()"
  },
  {
    "method": "removeFieldAt",
    "kind": "document",
    "parameters": [
      "pos"
    ],
    "signature": "removeFieldAt(pos: DocumentPosition)"
  },
  {
    "method": "removeHyperlink",
    "kind": "document",
    "parameters": [
      "target",
      "fieldId",
      "restoreFormatting"
    ],
    "signature": "removeHyperlink(target: HyperlinkTarget, fieldId: number, restoreFormatting = false)"
  },
  {
    "method": "renameBookmark",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ctrlIdx",
      "newName"
    ],
    "signature": "renameBookmark(sec: number, para: number, ctrlIdx: number, newName: string)"
  },
  {
    "method": "replaceAll",
    "kind": "document",
    "parameters": [
      "query",
      "newText",
      "caseSensitive"
    ],
    "signature": "replaceAll(query: string, newText: string, caseSensitive: boolean)"
  },
  {
    "method": "replaceBodyTextLocal",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "deleteCount",
      "text",
      "logical"
    ],
    "signature": "replaceBodyTextLocal(sec: number, para: number, charOffset: number, deleteCount: number, text: string, logical = false,)"
  },
  {
    "method": "replaceHyperlinkText",
    "kind": "document",
    "parameters": [
      "target",
      "fieldId",
      "text"
    ],
    "signature": "replaceHyperlinkText(target: HyperlinkTarget, fieldId: number, text: string)"
  },
  {
    "method": "replaceOne",
    "kind": "document",
    "parameters": [
      "query",
      "newText",
      "caseSensitive"
    ],
    "signature": "replaceOne(query: string, newText: string, caseSensitive: boolean)"
  },
  {
    "method": "replaceRangeInHeaderFooter",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "startHfParaIdx",
      "startOffset",
      "endHfParaIdx",
      "endOffset",
      "replacementText"
    ],
    "signature": "replaceRangeInHeaderFooter(sec: number, isHeader: boolean, applyTo: number, startHfParaIdx: number, startOffset: number, endHfParaIdx: number, endOffset: number, replacementText: string,)"
  },
  {
    "method": "replaceText",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "length",
      "newText"
    ],
    "signature": "replaceText(sec: number, para: number, charOffset: number, length: number, newText: string)"
  },
  {
    "method": "replaceTextInCellDeferredPagination",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "charOffset",
      "deleteCount",
      "text",
      "logical"
    ],
    "signature": "replaceTextInCellDeferredPagination(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, charOffset: number, deleteCount: number, text: string, logical = false,)"
  },
  {
    "method": "resizeTableCells",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "updates"
    ],
    "signature": "resizeTableCells(sec: number, parentPara: number, controlIdx: number, updates: TableCellResizeUpdate[],)"
  },
  {
    "method": "resizeTableCellsByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "updates"
    ],
    "signature": "resizeTableCellsByPath(sec: number, parentPara: number, pathJson: string, updates: TableCellResizeUpdate[],)"
  },
  {
    "method": "setCellParaShapeId",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "paraShapeId"
    ],
    "signature": "setCellParaShapeId(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, paraShapeId: number)"
  },
  {
    "method": "setCellParaShapeIdByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "path",
      "shapeId"
    ],
    "signature": "setCellParaShapeIdByPath(sec: number, parentPara: number, path: string, shapeId: number)"
  },
  {
    "method": "setCellPicturePropertiesByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "cellPath",
      "innerControlIdx",
      "props"
    ],
    "signature": "setCellPicturePropertiesByPath(sec: number, parentPara: number, cellPath: CellPathLike, innerControlIdx: number, props: Record<string, unknown>,)"
  },
  {
    "method": "setCellProperties",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "props"
    ],
    "signature": "setCellProperties(sec: number, parentPara: number, controlIdx: number, cellIdx: number, props: Partial<CellProperties>)"
  },
  {
    "method": "setCellShapePropertiesByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "cellPath",
      "innerControlIdx",
      "props"
    ],
    "signature": "setCellShapePropertiesByPath(sec: number, parentPara: number, cellPath: CellPathLike, innerControlIdx: number, props: Record<string, unknown>,)"
  },
  {
    "method": "setCellZoneProperties",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "range",
      "props"
    ],
    "signature": "setCellZoneProperties(sec: number, parentPara: number, controlIdx: number, range: { startRow: number; startCol: number; endRow: number; endCol: number }, props: Partial<CellProperties>,)"
  },
  {
    "method": "setCharShapeId",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "startOffset",
      "endOffset",
      "charShapeId"
    ],
    "signature": "setCharShapeId(sec: number, para: number, startOffset: number, endOffset: number, charShapeId: number)"
  },
  {
    "method": "setCharShapeIdInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "startOffset",
      "endOffset",
      "charShapeId"
    ],
    "signature": "setCharShapeIdInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, startOffset: number, endOffset: number, charShapeId: number)"
  },
  {
    "method": "setCharShapeIdInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "startOffset",
      "endOffset",
      "charShapeId"
    ],
    "signature": "setCharShapeIdInCellByPath(sec: number, parentPara: number, pathJson: string, startOffset: number, endOffset: number, charShapeId: number)"
  },
  {
    "method": "setCharShapeIdInFootnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "control",
      "notePara",
      "start",
      "end",
      "shapeId"
    ],
    "signature": "setCharShapeIdInFootnote(sec: number, para: number, control: number, notePara: number, start: number, end: number, shapeId: number)"
  },
  {
    "method": "setCharShapeIdInHf",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "para",
      "start",
      "end",
      "shapeId"
    ],
    "signature": "setCharShapeIdInHf(sec: number, isHeader: boolean, applyTo: number, para: number, start: number, end: number, shapeId: number)"
  },
  {
    "method": "setCharShapeRuns",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "start",
      "end",
      "runs"
    ],
    "signature": "setCharShapeRuns(sec: number, para: number, start: number, end: number, runs: CharShapeRun[])"
  },
  {
    "method": "setCharShapeRunsInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "path",
      "start",
      "end",
      "runs"
    ],
    "signature": "setCharShapeRunsInCellByPath(sec: number, para: number, path: string, start: number, end: number, runs: CharShapeRun[])"
  },
  {
    "method": "setColumnDef",
    "kind": "document",
    "parameters": [
      "sec",
      "columnCount",
      "columnType",
      "sameWidth",
      "spacingHu"
    ],
    "signature": "setColumnDef(sec: number, columnCount: number, columnType: number, sameWidth: number, spacingHu: number)"
  },
  {
    "method": "setEquationProperties",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci",
      "cellIdx",
      "cellParaIdx",
      "props",
      "innerControlIdx"
    ],
    "signature": "setEquationProperties(sec: number, para: number, ci: number, cellIdx: number | undefined, cellParaIdx: number | undefined, props: Record<string, unknown>, innerControlIdx?: number)"
  },
  {
    "method": "setEquationPropertiesByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "cellPath",
      "innerControlIdx",
      "props"
    ],
    "signature": "setEquationPropertiesByPath(sec: number, parentPara: number, cellPath: CellPathLike, innerControlIdx: number, props: Record<string, unknown>)"
  },
  {
    "method": "setFieldValue",
    "kind": "document",
    "parameters": [
      "fieldId",
      "value"
    ],
    "signature": "setFieldValue(fieldId: number, value: string)"
  },
  {
    "method": "setFieldValueByName",
    "kind": "document",
    "parameters": [
      "name",
      "value"
    ],
    "signature": "setFieldValueByName(name: string, value: string)"
  },
  {
    "method": "setFormValue",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci",
      "valueJson"
    ],
    "signature": "setFormValue(sec: number, para: number, ci: number, valueJson: string)"
  },
  {
    "method": "setFormValueInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "tablePara",
      "tableCi",
      "cellIdx",
      "cellPara",
      "formCi",
      "valueJson"
    ],
    "signature": "setFormValueInCell(sec: number, tablePara: number, tableCi: number, cellIdx: number, cellPara: number, formCi: number, valueJson: string)"
  },
  {
    "method": "setHeaderFooterPictureProperties",
    "kind": "document",
    "parameters": [
      "sec",
      "outerPara",
      "outerCtrl",
      "innerPara",
      "innerCtrl",
      "props"
    ],
    "signature": "setHeaderFooterPictureProperties(sec: number, outerPara: number, outerCtrl: number, innerPara: number, innerCtrl: number, props: Record<string, unknown>,)"
  },
  {
    "method": "setNoteEquationProperties",
    "kind": "document",
    "parameters": [
      "noteRef",
      "props"
    ],
    "signature": "setNoteEquationProperties(noteRef: import('./types').NoteControlRef, props: Record<string, unknown>)"
  },
  {
    "method": "setNumberingRestart",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "mode",
      "startNum"
    ],
    "signature": "setNumberingRestart(sec: number, para: number, mode: number, startNum: number)"
  },
  {
    "method": "setPageBorderFill",
    "kind": "document",
    "parameters": [
      "sectionIdx",
      "settings"
    ],
    "signature": "setPageBorderFill(sectionIdx: number, settings: PageBorderFillSettings)"
  },
  {
    "method": "setPageDef",
    "kind": "document",
    "parameters": [
      "sectionIdx",
      "pageDef"
    ],
    "signature": "setPageDef(sectionIdx: number, pageDef: PageDef)"
  },
  {
    "method": "setPageHide",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "hideHeader",
      "hideFooter",
      "hideMaster",
      "hideBorder",
      "hideFill",
      "hidePageNum"
    ],
    "signature": "setPageHide(sec: number, para: number, hideHeader: boolean, hideFooter: boolean, hideMaster: boolean, hideBorder: boolean, hideFill: boolean, hidePageNum: boolean,)"
  },
  {
    "method": "setParaShapeId",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "paraShapeId"
    ],
    "signature": "setParaShapeId(sec: number, para: number, paraShapeId: number)"
  },
  {
    "method": "setParaShapeIdInFootnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "control",
      "notePara",
      "shapeId"
    ],
    "signature": "setParaShapeIdInFootnote(sec: number, para: number, control: number, notePara: number, shapeId: number)"
  },
  {
    "method": "setParaShapeIdInHf",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "para",
      "shapeId"
    ],
    "signature": "setParaShapeIdInHf(sec: number, isHeader: boolean, applyTo: number, para: number, shapeId: number)"
  },
  {
    "method": "setPictureProperties",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci",
      "props"
    ],
    "signature": "setPictureProperties(sec: number, para: number, ci: number, props: Record<string, unknown>)"
  },
  {
    "method": "setSectionDef",
    "kind": "document",
    "parameters": [
      "sectionIdx",
      "sectionDef"
    ],
    "signature": "setSectionDef(sectionIdx: number, sectionDef: SectionDef)"
  },
  {
    "method": "setSectionDefAll",
    "kind": "document",
    "parameters": [
      "sectionDef"
    ],
    "signature": "setSectionDefAll(sectionDef: SectionDef)"
  },
  {
    "method": "setShapeProperties",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci",
      "props"
    ],
    "signature": "setShapeProperties(sec: number, para: number, ci: number, props: Record<string, unknown>)"
  },
  {
    "method": "setTableCaptionText",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "text",
      "withNumber"
    ],
    "signature": "setTableCaptionText(sec: number, parentPara: number, controlIdx: number, text: string, withNumber: boolean)"
  },
  {
    "method": "setTableColumnWidths",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "widths"
    ],
    "signature": "setTableColumnWidths(sec: number, parentPara: number, controlIdx: number, widths: number[])"
  },
  {
    "method": "setTableProperties",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "props"
    ],
    "signature": "setTableProperties(sec: number, parentPara: number, controlIdx: number, props: Partial<TableProperties>)"
  },
  {
    "method": "splitParagraph",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset",
      "removedParaMeta"
    ],
    "signature": "splitParagraph(sec: number, para: number, charOffset: number, removedParaMeta?: RemovedParaMeta)"
  },
  {
    "method": "splitParagraphInCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "charOffset",
      "removedParaMeta"
    ],
    "signature": "splitParagraphInCell(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, charOffset: number, removedParaMeta?: RemovedParaMeta)"
  },
  {
    "method": "splitParagraphInCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "charOffset",
      "removedParaMeta"
    ],
    "signature": "splitParagraphInCellByPath(sec: number, parentPara: number, pathJson: string, charOffset: number, removedParaMeta?: RemovedParaMeta)"
  },
  {
    "method": "splitParagraphInCellLogical",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "cellIdx",
      "cellParaIdx",
      "charOffset"
    ],
    "signature": "splitParagraphInCellLogical(sec: number, parentPara: number, controlIdx: number, cellIdx: number, cellParaIdx: number, charOffset: number)"
  },
  {
    "method": "splitParagraphInFootnote",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "controlIdx",
      "fnParaIdx",
      "charOffset",
      "removedParaMeta"
    ],
    "signature": "splitParagraphInFootnote(sec: number, para: number, controlIdx: number, fnParaIdx: number, charOffset: number, removedParaMeta?: RemovedParaMeta)"
  },
  {
    "method": "splitParagraphInHeaderFooter",
    "kind": "document",
    "parameters": [
      "sec",
      "isHeader",
      "applyTo",
      "hfParaIdx",
      "charOffset",
      "removedParaMeta"
    ],
    "signature": "splitParagraphInHeaderFooter(sec: number, isHeader: boolean, applyTo: number, hfParaIdx: number, charOffset: number, removedParaMeta?: RemovedParaMeta)"
  },
  {
    "method": "splitParagraphLogical",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "charOffset"
    ],
    "signature": "splitParagraphLogical(sec: number, para: number, charOffset: number)"
  },
  {
    "method": "splitTableCell",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "row",
      "col"
    ],
    "signature": "splitTableCell(sec: number, parentPara: number, controlIdx: number, row: number, col: number)"
  },
  {
    "method": "splitTableCellByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "row",
      "col"
    ],
    "signature": "splitTableCellByPath(sec: number, parentPara: number, pathJson: string, row: number, col: number)"
  },
  {
    "method": "splitTableCellInto",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "row",
      "col",
      "nRows",
      "mCols",
      "equalRowHeight",
      "mergeFirst"
    ],
    "signature": "splitTableCellInto(sec: number, parentPara: number, controlIdx: number, row: number, col: number, nRows: number, mCols: number, equalRowHeight: boolean, mergeFirst: boolean,)"
  },
  {
    "method": "splitTableCellIntoByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "row",
      "col",
      "nRows",
      "mCols",
      "equalRowHeight",
      "mergeFirst"
    ],
    "signature": "splitTableCellIntoByPath(sec: number, parentPara: number, pathJson: string, row: number, col: number, nRows: number, mCols: number, equalRowHeight: boolean, mergeFirst: boolean,)"
  },
  {
    "method": "splitTableCellsInRange",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx",
      "startRow",
      "startCol",
      "endRow",
      "endCol",
      "nRows",
      "mCols",
      "equalRowHeight"
    ],
    "signature": "splitTableCellsInRange(sec: number, parentPara: number, controlIdx: number, startRow: number, startCol: number, endRow: number, endCol: number, nRows: number, mCols: number, equalRowHeight: boolean,)"
  },
  {
    "method": "splitTableCellsInRangeByPath",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "pathJson",
      "startRow",
      "startCol",
      "endRow",
      "endCol",
      "nRows",
      "mCols",
      "equalRowHeight"
    ],
    "signature": "splitTableCellsInRangeByPath(sec: number, parentPara: number, pathJson: string, startRow: number, startCol: number, endRow: number, endCol: number, nRows: number, mCols: number, equalRowHeight: boolean,)"
  },
  {
    "method": "toggleHideHeaderFooter",
    "kind": "session",
    "parameters": [
      "pageIndex",
      "isHeader"
    ],
    "signature": "toggleHideHeaderFooter(pageIndex: number, isHeader: boolean)"
  },
  {
    "method": "transposeTableCellsInPlace",
    "kind": "document",
    "parameters": [
      "sec",
      "parentPara",
      "controlIdx"
    ],
    "signature": "transposeTableCellsInPlace(sec: number, parentPara: number, controlIdx: number,)"
  },
  {
    "method": "ungroupShape",
    "kind": "document",
    "parameters": [
      "sec",
      "para",
      "ci"
    ],
    "signature": "ungroupShape(sec: number, para: number, ci: number)"
  },
  {
    "method": "updateClickHereProps",
    "kind": "document",
    "parameters": [
      "fieldId",
      "guide",
      "memo",
      "name",
      "editable"
    ],
    "signature": "updateClickHereProps(fieldId: number, guide: string, memo: string, name: string, editable: boolean)"
  },
  {
    "method": "updateConnectorsInSection",
    "kind": "document",
    "parameters": [
      "sec"
    ],
    "signature": "updateConnectorsInSection(sec: number)"
  },
  {
    "method": "updateHyperlink",
    "kind": "document",
    "parameters": [
      "target",
      "fieldId",
      "uri"
    ],
    "signature": "updateHyperlink(target: HyperlinkTarget, fieldId: number, uri: string)"
  },
  {
    "method": "updateStyle",
    "kind": "document",
    "parameters": [
      "styleId",
      "json"
    ],
    "signature": "updateStyle(styleId: number, json: string)"
  },
  {
    "method": "updateStyleShapes",
    "kind": "document",
    "parameters": [
      "styleId",
      "charModsJson",
      "paraModsJson"
    ],
    "signature": "updateStyleShapes(styleId: number, charModsJson: string, paraModsJson: string)"
  }
] as const;
export const ENGINE_EDIT_TYPE_DEFINITIONS = {
  "CharProperties": "export interface CharProperties { fontFamily?: string; fontSize?: number; bold?: boolean; italic?: boolean; underline?: boolean; strikethrough?: boolean; textColor?: string; shadeColor?: string; emboss?: boolean; engrave?: boolean; charShapeId?: number; fontId?: number; fontIds?: number[]; underlineType?: string; underlineColor?: string; outlineType?: number; shadowType?: number; shadowColor?: string; shadowOffsetX?: number; shadowOffsetY?: number; strikeColor?: string; subscript?: boolean; superscript?: boolean; fontFamilies?: string[]; ratios?: number[]; spacings?: number[]; relativeSizes?: number[]; charOffsets?: number[]; fontName?: string; emphasisDot?: number; underlineShape?: number; strikeShape?: number; kerning?: boolean; borderFillId?: number; borderLeft?: { type: number; width: number; color: string }; borderRight?: { type: number; width: number; color: string }; borderTop?: { type: number; width: number; color: string }; borderBottom?: { type: number; width: number; color: string }; fillType?: string; fillColor?: string; patternColor?: string; patternType?: number; }",
  "ParaProperties": "export interface ParaProperties { alignment?: string; lineSpacing?: number; lineSpacingType?: string; marginLeft?: number; marginRight?: number; indent?: number; spacingBefore?: number; spacingAfter?: number; paraShapeId?: number; headType?: string; paraLevel?: number; numberingId?: number; widowOrphan?: boolean; keepWithNext?: boolean; keepLines?: boolean; pageBreakBefore?: boolean; fontLineHeight?: boolean; singleLine?: boolean; autoSpaceKrEn?: boolean; autoSpaceKrNum?: boolean; verticalAlign?: number; englishBreakUnit?: number; koreanBreakUnit?: number; tabAutoLeft?: boolean; tabAutoRight?: boolean; tabStops?: { position: number; type: number; fill: number }[]; defaultTabSpacing?: number; borderFillId?: number; borderLeft?: { type: number; width: number; color: string }; borderRight?: { type: number; width: number; color: string }; borderTop?: { type: number; width: number; color: string }; borderBottom?: { type: number; width: number; color: string }; fillType?: string; fillColor?: string; patternColor?: string; patternType?: number; borderSpacing?: number[]; borderConnect?: boolean; borderIgnoreMargin?: boolean; }",
  "ShapeProperties": "export interface ShapeProperties { width: number; height: number; treatAsChar: boolean; vertRelTo: string; vertAlign: string; horzRelTo: string; horzAlign: string; vertOffset: number; horzOffset: number; textWrap: string; sizeProtect?: boolean; tbMarginLeft?: number; tbMarginRight?: number; tbMarginTop?: number; tbMarginBottom?: number; tbVerticalAlign?: string; borderColor?: number; borderWidth?: number; borderAttr?: number; borderOutlineStyle?: number; lineType?: number; lineEndShape?: number; arrowStart?: number; arrowEnd?: number; arrowStartSize?: number; arrowEndSize?: number; rotationAngle?: number; horzFlip?: boolean; vertFlip?: boolean; fillType?: string; fillBgColor?: number; fillPatColor?: number; fillPatType?: number; fillAlpha?: number; gradientType?: number; gradientAngle?: number; gradientCenterX?: number; gradientCenterY?: number; gradientBlur?: number; roundRate?: number; description: string; }",
  "PictureProperties": "export interface PictureProperties { width: number; height: number; treatAsChar: boolean; vertRelTo: string; vertAlign: string; horzRelTo: string; horzAlign: string; vertOffset: number; horzOffset: number; textWrap: string; restrictInPage?: boolean; allowOverlap?: boolean; sizeProtect?: boolean; brightness: number; contrast: number; effect: string; transparency?: number; description: string; rotationAngle: number; horzFlip: boolean; vertFlip: boolean; originalWidth: number; originalHeight: number; cropLeft: number; cropTop: number; cropRight: number; cropBottom: number; paddingLeft: number; paddingTop: number; paddingRight: number; paddingBottom: number; outerMarginLeft: number; outerMarginTop: number; outerMarginRight: number; outerMarginBottom: number; borderColor: number; borderWidth: number; hasCaption: boolean; captionDirection: string; captionVertAlign: string; captionWidth: number; captionSpacing: number; captionMaxWidth: number; captionIncludeMargin: boolean; externalPath?: string; }",
  "EquationProperties": "export interface EquationProperties { width?: number; height?: number; treatAsChar?: boolean; vertRelTo?: string; vertAlign?: string; horzRelTo?: string; horzAlign?: string; vertOffset?: number; horzOffset?: number; textWrap?: string; sizeProtect?: boolean; zOrder?: number; instanceId?: number; outerMarginLeft?: number; outerMarginTop?: number; outerMarginRight?: number; outerMarginBottom?: number; hasCaption?: boolean; captionDirection?: string; captionWidth?: number; captionSpacing?: number; description?: string; script: string; fontSize: number; color: number; baseline: number; fontName: string; }",
  "EndnoteShapeSettings": "export interface EndnoteShapeSettings { ok?: boolean; numberFormat: EndnoteNumberFormat | string; userChar: string; prefixChar: string; suffixChar: string; startNumber: number; separatorEnabled: boolean; separatorLength: number; separatorMarginTop: number; separatorMarginBottom: number; noteSpacing: number; separatorLineType: number; separatorLineWidth: number; separatorColor: string; numbering: 'continue' | 'restartSection' | 'restartPage' | string; placement: 'documentEnd' | 'sectionEnd' | string; }",
  "CellPathLike": "export type CellPathLike = Array<CellPathEntry | CellPathSegment>;",
  "DocumentPosition": "export interface DocumentPosition { sectionIndex: number; paragraphIndex: number; charOffset: number; parentParaIndex?: number; controlIndex?: number; cellIndex?: number; cellParaIndex?: number; cellPath?: CellPathEntry[]; isTextBox?: boolean; cursorRect?: CursorRect; }",
  "TableCellResizeUpdate": "export interface TableCellResizeUpdate { cellIdx: number; widthDelta?: number; heightDelta?: number; localResize?: boolean; renderWidth?: number; renderHeight?: number; }",
  "CellProperties": "export interface CellProperties { width: number; height: number; paddingLeft: number; paddingRight: number; paddingTop: number; paddingBottom: number; applyInnerMargin: boolean; verticalAlign: number; textDirection: number; isHeader: boolean; cellProtect?: boolean; fieldName?: string; editableInForm?: boolean; borderFillId?: number; borderLeft?: BorderLineInfo; borderRight?: BorderLineInfo; borderTop?: BorderLineInfo; borderBottom?: BorderLineInfo; fillType?: string; fillColor?: string; patternColor?: string; patternType?: number; diagonalLine?: number; diagonalSlash?: number; diagonalBackSlash?: number; diagonalWidth?: number; diagonalColor?: string; centerLine?: string; }",
  "CharShapeRun": "export interface CharShapeRun { startOffset: number; endOffset: number; charShapeId: number; }",
  "NoteControlRef": "export interface NoteControlRef { kind: 'footnote' | 'endnote'; sectionIdx: number; paraIdx: number; controlIdx: number; noteParaIdx: number; innerControlIdx: number; }",
  "PageBorderFillSettings": "export interface PageBorderFillSettings { attr: number; basis: 'paper' | 'page'; spacingLeft: number; spacingRight: number; spacingTop: number; spacingBottom: number; borderFillId: number; headerInside: boolean; footerInside: boolean; fillArea: 'paper' | 'page' | 'border'; hideBorder: boolean; hideFill: boolean; borderLeft: BorderLineProps; borderRight: BorderLineProps; borderTop: BorderLineProps; borderBottom: BorderLineProps; fillType: 'none' | 'solid' | string; fillColor: string; patternColor: string; patternType: number; applyPage?: 'all' | 'exceptFirst' | 'firstOnly'; }",
  "PageDef": "export interface PageDef { width: number; height: number; marginLeft: number; marginRight: number; marginTop: number; marginBottom: number; marginHeader: number; marginFooter: number; marginGutter: number; landscape: boolean; binding: number; }",
  "SectionDef": "export interface SectionDef { pageNum: number; pageNumType: number; pictureNum: number; tableNum: number; equationNum: number; columnSpacing: number; defaultTabSpacing: number; hideHeader: boolean; hideFooter: boolean; hideMasterPage: boolean; hideBorder: boolean; hideFill: boolean; hideEmptyLine: boolean; }",
  "TableProperties": "export interface TableProperties { cellSpacing: number; paddingLeft: number; paddingRight: number; paddingTop: number; paddingBottom: number; pageBreak: number; repeatHeader: boolean; tableWidth?: number; tableHeight?: number; outerLeft?: number; outerRight?: number; outerTop?: number; outerBottom?: number; hasCaption?: boolean; captionDirection?: number; captionVertAlign?: number; captionWidth?: number; captionSpacing?: number; treatAsChar?: boolean; textWrap?: string; vertRelTo?: string; vertAlign?: string; horzRelTo?: string; horzAlign?: string; vertOffset?: number; horzOffset?: number; restrictInPage?: boolean; allowOverlap?: boolean; keepWithAnchor?: boolean; borderFillId?: number; borderLeft?: BorderLineInfo; borderRight?: BorderLineInfo; borderTop?: BorderLineInfo; borderBottom?: BorderLineInfo; fillType?: string; fillColor?: string; patternColor?: string; patternType?: number; }",
  "RemovedParaMeta": "export type RemovedParaMeta = Record<string, unknown>;",
  "EndnoteNumberFormat": "export type EndnoteNumberFormat = | 'digit' | 'circledDigit' | 'upperRoman' | 'lowerRoman' | 'upperAlpha' | 'lowerAlpha' | 'hangulSyllable' | 'hangulJamo' | 'hangulDigit' | 'hanjaDigit';",
  "CellPathEntry": "export interface CellPathEntry { controlIndex: number; cellIndex: number; cellParaIndex: number; }",
  "CellPathSegment": "export interface CellPathSegment { controlIdx: number; cellIdx: number; cellParaIdx: number; }",
  "CursorRect": "export interface CursorRect { pageIndex: number; x: number; y: number; height: number; cellBounds?: { x: number; y: number; w: number; h: number }; cellOverflowed?: boolean; }",
  "BorderLineInfo": "export interface BorderLineInfo { type: number; width: number; color: string; }",
  "BorderLineProps": "export interface BorderLineProps { type: number; width: number; color: string; }"
} as const;
